export const ADD_TO_CART_GUEST = "ADD_TO_CART_GUEST";
export const ADD_TO_CART_USER = "ADD_TO_CART_USER ";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const REMOVE_CART_ITEM_USER = "REMOVE_CART_ITEM_USER";
export const SET_CART_USER_ITEMS = "SET_CART_USER_ITEMS";
export const EMPTY_SHIPPING_INFO = "EMPTY_SHIPPING_INFO";
